### ISSUE TITLE
Is it possible to load the checkpoint you provided in regular ResNet50? 

### ISSUE THREAD

**Issue by anonydeven** [1adrianb/unsupervised-face-representation#1]
Is it possible to load the checkpoint you provided in regular ResNet50?  I have tried to load the pth file you have provided in ResNet50 and I am not able to do it.

**Comment by enesozi** [comment]
@anonydeven You can do it with the below code snippet:
```python
from archs import resnet50
from models import SwAVNet

base_model = resnet50().eval().to("cpu")
model = SwAVNet(base_model, 
            projection_hidden_size=2048,
            num_prototypes=3000, projection_size=128
            ).eval().to("cpu")

# Download a pre-trained model and load it
state_dict_old = torch.load("flr_r50_vgg_face_1m.pth", map_location="cpu")["state_dict"]
state_dict = {}
for key, value in state_dict_old.items():
    key = key[7:]
    state_dict[key] = value
model.load_state_dict(state_dict,strict=True)

with torch.no_grad():
    inp = torch.randn(1,3,512,512).to("cpu")
    res = model(inp)

# If you want only the ResNet part - it's missing the last classifier(linear) layer
resnet = model.base_net
```

**Comment by Kitopvibe1** [comment]
> @anonydeven You can do it with the below code snippet:
> 
> ```python
> from archs import resnet50
> from models import SwAVNet
> 
> base_model = resnet50().eval().to("cpu")
> model = SwAVNet(base_model, 
>             projection_hidden_size=2048,
>             num_prototypes=3000, projection_size=128
>             ).eval().to("cpu")
> 
> # Download a pre-trained model and load it
> state_dict_old = torch.load("flr_r50_vgg_face_1m.pth", map_location="cpu")["state_dict"]
> state_dict = {}
> for key, value in state_dict_old.items():
>     key = key[7:]
>     state_dict[key] = value
> model.load_state_dict(state_dict,strict=True)
> 
> with torch.no_grad():
>     inp = torch.randn(1,3,512,512).to("cpu")
>     res = model(inp)
> 
> # If you want only the ResNet part - it's missing the last classifier(linear) layer
> resnet = model.base_net
> ```

not working

**Comment by Kitopvibe1** [comment]
i need  the archs.py file containing the resnet50 architecture of the checkpoint

**Comment by 1adrianb** [comment]
Thank @enesozi the code should indeed look alike. It generally depends if you want to reuse the projections used for pretraining or discard them. Added an example in the readme.
