### ISSUE TITLE
Using pretrained models to get embeddings for my own images

### ISSUE THREAD

**Issue by TehreemFarooqi** [1adrianb/unsupervised-face-representation#5]
Hi @1adrianb, I want to use the pretrained models you have given to generate embeddings for my own images. Can you guide me on how to pre-process my images so your model would accept them and how to load and use your models? If you have a broilerplate code, that will be best. Otherwise, please point me to the code in your repo that does image preprocessing so I can replicate it for inference.

**Comment by 1adrianb** [comment]
Hi @TehreemFarooqi 

For post-processing you can use Imagenet-style pre-processing:

```python
normalize = transforms.Normalize(mean=[0.485, 0.456, 0.406],
                                     std=[0.229, 0.224, 0.225])
transforms.Compose([
       transforms.Resize(256),
       transforms.CenterCrop(224),
       transforms.ToTensor(),
       normalize,
]))
```
